import { LoaderCircle, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { CreateDeliveryInput, PackageListData } from './operation.types';
import { packageTypeLabels } from './operation.types';

function localDateTime() { const date = new Date(); const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }

export function DeliveryFormDialog({ data, pending, onClose, onSubmit }: { data: PackageListData; pending: boolean; onClose: () => void; onSubmit: (input: CreateDeliveryInput) => Promise<void> }) {
  const available = data.packages.filter((item) => !item.deliveryId);
  const [selected, setSelected] = useState<string[]>([]); const [deliveredAt, setDeliveredAt] = useState(localDateTime); const [receiverName, setReceiverName] = useState(''); const [notes, setNotes] = useState('');
  const selectedPackages = useMemo(() => available.filter((item) => selected.includes(item.id)), [available, selected]);
  const total = selectedPackages.reduce((sum, item) => sum + item.quantity, 0);
  const submit = () => onSubmit({ workOrderId: data.workOrder.id, packageIds: selected, deliveredAt: new Date(deliveredAt).toISOString(), receiverName: receiverName.trim() || null, notes: notes.trim() || null });
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/65 p-0 sm:p-4"><section role="dialog" aria-modal="true" aria-labelledby="delivery-form-title" tabIndex={-1} autoFocus onKeyDown={(event) => event.key === 'Escape' && !pending && onClose()} className="h-full w-full overflow-y-auto border-[var(--zeva-border-strong)] bg-[var(--zeva-surface)] p-5 shadow-2xl sm:h-auto sm:max-h-[90vh] sm:max-w-2xl sm:rounded-xl sm:border sm:p-6"><header className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--zeva-accent)]">Teslimat</p><h2 id="delivery-form-title" className="mt-1 text-xl font-semibold text-white">Yeni teslimat</h2><p className="mt-1 text-sm text-[var(--zeva-text-muted)]">{data.workOrder.productName} · {data.workOrder.customer.name}</p></div><button type="button" aria-label="Teslimat penceresini kapat" onClick={onClose} className="grid size-10 place-items-center rounded-lg text-[#929b94]"><X className="size-5" /></button></header>
    <fieldset className="mt-5"><legend className="text-sm font-medium text-[#dce2dd]">Teslim edilecek paketler</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{available.map((item) => <label key={item.id} className={`flex min-h-14 cursor-pointer items-center gap-3 rounded-lg border p-3 ${selected.includes(item.id) ? 'border-[var(--zeva-accent)] bg-[#1c2920]' : 'border-[var(--zeva-border)] bg-[#111512]'}`}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])} className="size-4 accent-[var(--zeva-accent)]" /><span className="min-w-0 flex-1 text-sm text-[#dce2dd]">{packageTypeLabels[item.type]} #{item.sequenceNo}</span><strong className="text-sm text-white">{item.quantity.toLocaleString('tr-TR')} adet</strong></label>)}</div>{available.length === 0 ? <p className="mt-2 rounded-lg border border-dashed border-[var(--zeva-border)] p-4 text-sm text-[var(--zeva-text-muted)]">Teslim edilebilecek paket bulunmuyor.</p> : null}</fieldset>
    <div className="mt-4 rounded-lg border border-[#36503d] bg-[#19231c] px-4 py-3 text-sm text-[#cfdfd3]"><strong>{selected.length} paket</strong> · {total.toLocaleString('tr-TR')} adet seçildi</div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label htmlFor="delivery-date" className="text-sm text-[#d8ded9]">Teslim tarihi</label><input id="delivery-date" type="datetime-local" value={deliveredAt} onChange={(e) => setDeliveredAt(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-lg border border-[var(--zeva-border-strong)] bg-[#111512] px-3 text-white" /></div><div><label htmlFor="receiver-name" className="text-sm text-[#d8ded9]">Teslim alan kişi</label><input id="receiver-name" value={receiverName} onChange={(e) => setReceiverName(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-lg border border-[var(--zeva-border-strong)] bg-[#111512] px-3 text-white" /></div></div><div className="mt-4"><label htmlFor="delivery-notes" className="text-sm text-[#d8ded9]">Notlar</label><textarea id="delivery-notes" rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} className="mt-1.5 w-full rounded-lg border border-[var(--zeva-border-strong)] bg-[#111512] p-3 text-sm text-white" /></div>
    <footer className="mt-6 flex justify-end gap-2 border-t border-[var(--zeva-border)] pt-5"><button type="button" onClick={onClose} className="min-h-10 rounded-lg border border-[var(--zeva-border-strong)] px-4 text-sm text-[#cbd2cc]">Vazgeç</button><button type="button" disabled={pending || selected.length === 0 || !deliveredAt} onClick={() => void submit()} className="flex min-h-10 items-center gap-2 rounded-lg bg-[var(--zeva-accent)] px-4 text-sm font-semibold text-[#0d140f] disabled:opacity-50">{pending ? <LoaderCircle className="size-4 animate-spin" /> : null} Teslimatı oluştur</button></footer></section></div>;
}
