import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import type { PropsWithChildren } from 'react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ConfirmationContext, type ConfirmationContextValue } from '../../contexts/confirmation-context';
import { ToastContext, type ToastContextValue } from '../../contexts/toast-context';
import { useCustomerList } from '../customers/customer.queries';
import { useWorkOrderList } from '../work-orders/work-order.queries';
import type { WorkOrder } from '../work-orders/work-order.types';
import { OperationPage } from './operation-page';
import { useCancelDelivery, useCreateDelivery, useCreatePackages, useDeletePackage, useDeliveryDetail, useDeliveryList, usePackageList, useUpdatePackage } from './operation.queries';
import type { Delivery, PackageListData } from './operation.types';

vi.mock('../work-orders/work-order.queries', () => ({ useWorkOrderList: vi.fn() }));
vi.mock('../customers/customer.queries', () => ({ useCustomerList: vi.fn() }));
vi.mock('./operation.queries', () => ({
  usePackageList: vi.fn(), useCreatePackages: vi.fn(), useUpdatePackage: vi.fn(), useDeletePackage: vi.fn(),
  useDeliveryList: vi.fn(), useDeliveryDetail: vi.fn(), useCreateDelivery: vi.fn(), useCancelDelivery: vi.fn(),
}));

const workOrder: WorkOrder = { id: 'work-order-1', customerId: 'customer-1', customer: { id: 'customer-1', name: 'Alpha Tekstil' }, productName: 'Galatasaray Garson', type: 'IRONING_PACKAGING', status: 'READY', totalQuantity: 1000, unitPrice: '1.25', totalAmount: '1250.00', receivedAt: '2026-08-12T08:00:00.000Z', dueAt: null, notes: null, createdAt: '2026-08-12T08:00:00.000Z', updatedAt: '2026-08-12T08:00:00.000Z', deletedAt: null };
const packageData: PackageListData = { workOrder: { id: workOrder.id, productName: workOrder.productName, status: 'READY', totalQuantity: 1000, customer: workOrder.customer }, packages: [
  { id: 'package-1', workOrderId: workOrder.id, sequenceNo: 1, type: 'SACK', quantity: 250, deliveryId: null, delivery: null, notes: 'Kırmızı bağ', createdAt: workOrder.createdAt, updatedAt: workOrder.updatedAt, deletedAt: null },
  { id: 'package-2', workOrderId: workOrder.id, sequenceNo: 2, type: 'BOX', quantity: 250, deliveryId: 'delivery-1', delivery: { id: 'delivery-1', deliveredAt: workOrder.createdAt }, notes: null, createdAt: workOrder.createdAt, updatedAt: workOrder.updatedAt, deletedAt: null },
], summary: { workOrderTotalQuantity: 1000, packagedQuantity: 500, remainingQuantity: 500, deliveredQuantity: 250, packageCount: 2, deliveredPackageCount: 1 } };
const delivery: Delivery = { id: 'delivery-1', workOrderId: workOrder.id, workOrder: { id: workOrder.id, productName: workOrder.productName }, customer: workOrder.customer, totalQuantity: 250, deliveredAt: '2026-08-12T10:30:00.000Z', receiverName: 'Ahmet Yılmaz', notes: 'Müşteri teslim aldı.', cancelledAt: null, createdAt: workOrder.createdAt, updatedAt: workOrder.updatedAt, packages: [{ id: 'package-2', sequenceNo: 2, type: 'BOX', quantity: 250 }], packageCount: 1 };
const query = <T,>(data: T | undefined, extra: Record<string, unknown> = {}) => ({ data, isPending: false, isError: false, isFetching: false, isPlaceholderData: false, refetch: vi.fn(), ...extra });
const confirm = vi.fn<ConfirmationContextValue['confirm']>();
const toast: ToastContextValue = { show: vi.fn(() => 'id'), success: vi.fn(() => 'id'), error: vi.fn(() => 'id'), warning: vi.fn(() => 'id'), info: vi.fn(() => 'id'), dismiss: vi.fn() };
const createPackages = vi.fn<(input: { workOrderId: string; packages: Array<{ type: string; quantity: number; notes?: string | null }> }) => Promise<PackageListData>>();
const updatePackage = vi.fn<(input: { id: string; workOrderId: string; input: { type?: string; quantity?: number; notes?: string | null } }) => Promise<PackageListData['packages'][number]>>();
const deletePackage = vi.fn<(input: { id: string; workOrderId: string }) => Promise<Record<string, never>>>();
const createDelivery = vi.fn<(input: { workOrderId: string; packageIds: string[]; deliveredAt: string; receiverName: string | null; notes: string | null }) => Promise<Delivery>>();
const cancelDelivery = vi.fn<(id: string) => Promise<Delivery>>();
function Providers({ children }: PropsWithChildren) { return <MemoryRouter><ToastContext.Provider value={toast}><ConfirmationContext.Provider value={{ confirm }}>{children}</ConfirmationContext.Provider></ToastContext.Provider></MemoryRouter>; }
function configure(data: PackageListData | undefined = packageData) {
  vi.mocked(useWorkOrderList).mockReturnValue(query({ items: [workOrder], pagination: { page: 1, pageSize: 20, total: 1, totalPages: 1 } }) as unknown as ReturnType<typeof useWorkOrderList>);
  vi.mocked(useCustomerList).mockReturnValue(query({ items: [{ ...workOrder.customer, contactName: null, phone: null, address: null, notes: null, createdAt: workOrder.createdAt, updatedAt: workOrder.updatedAt, deletedAt: null }], pagination: { page: 1, pageSize: 20, total: 1, totalPages: 1 } }) as unknown as ReturnType<typeof useCustomerList>);
  vi.mocked(usePackageList).mockImplementation((id) => query(id ? data : undefined, id ? {} : { isPending: false }) as unknown as ReturnType<typeof usePackageList>);
  vi.mocked(useDeliveryList).mockReturnValue(query({ items: [delivery], pagination: { page: 1, pageSize: 20, total: 1, totalPages: 1 } }) as unknown as ReturnType<typeof useDeliveryList>);
  vi.mocked(useDeliveryDetail).mockReturnValue(query(delivery) as unknown as ReturnType<typeof useDeliveryDetail>);
  vi.mocked(useCreatePackages).mockReturnValue({ mutateAsync: createPackages, isPending: false } as unknown as ReturnType<typeof useCreatePackages>);
  vi.mocked(useUpdatePackage).mockReturnValue({ mutateAsync: updatePackage, isPending: false } as unknown as ReturnType<typeof useUpdatePackage>);
  vi.mocked(useDeletePackage).mockReturnValue({ mutateAsync: deletePackage, isPending: false } as unknown as ReturnType<typeof useDeletePackage>);
  vi.mocked(useCreateDelivery).mockReturnValue({ mutateAsync: createDelivery, isPending: false } as unknown as ReturnType<typeof useCreateDelivery>);
  vi.mocked(useCancelDelivery).mockReturnValue({ mutateAsync: cancelDelivery, isPending: false } as unknown as ReturnType<typeof useCancelDelivery>);
}
function selectWorkOrder() { const box = screen.getByRole('combobox', { name: 'İş emri' }); fireEvent.focus(box); fireEvent.click(screen.getByRole('option', { name: /Galatasaray Garson/ })); }

describe('OperationPage', () => {
  beforeEach(() => { vi.clearAllMocks(); confirm.mockResolvedValue(true); createPackages.mockResolvedValue(packageData); updatePackage.mockResolvedValue(packageData.packages[0]!); deletePackage.mockResolvedValue({}); createDelivery.mockResolvedValue(delivery); cancelDelivery.mockResolvedValue({ ...delivery, cancelledAt: workOrder.updatedAt }); configure(); });
  it('iş emri combobox aramasını debounce eder ve seçilen operasyon özetini gösterir', async () => { render(<OperationPage />, { wrapper: Providers }); fireEvent.change(screen.getByRole('combobox', { name: 'İş emri' }), { target: { value: 'Alpha' } }); await waitFor(() => expect(useWorkOrderList).toHaveBeenLastCalledWith(expect.objectContaining({ q: 'Alpha' }))); selectWorkOrder(); expect(await screen.findByText('Paketlenen')).toBeTruthy(); expect(screen.getAllByText('500').length).toBeGreaterThan(0); });
  it('iş emri seçilmemiş empty state gösterir', () => { render(<OperationPage />, { wrapper: Providers }); expect(screen.getByText('İş emri seçin')).toBeTruthy(); });
  it('paket loading ve error durumlarını gösterir', async () => { vi.mocked(usePackageList).mockReturnValue(query(undefined, { isPending: true }) as unknown as ReturnType<typeof usePackageList>); const { rerender } = render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); expect(await screen.findByLabelText('Paketler yükleniyor')).toBeTruthy(); vi.mocked(usePackageList).mockReturnValue(query(undefined, { isError: true }) as unknown as ReturnType<typeof usePackageList>); rerender(<OperationPage />); expect(screen.getByText('Paketler yüklenemedi')).toBeTruthy(); });
  it('batch satırı ekler/kaldırır ve kalan adet önizlemesini günceller', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); expect(await screen.findByText(/Eklenecek:/)).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Satır ekle' })); expect(screen.getByLabelText('2. satırı kaldır')).toBeTruthy(); fireEvent.click(screen.getByLabelText('2. satırı kaldır')); expect(screen.queryByLabelText('2. satırı kaldır')).toBeNull(); });
  it('hızlı adet girişini çuval satırlarına dönüştürür', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); const quick = await screen.findByLabelText('Hızlı adet girişi'); fireEvent.change(quick, { target: { value: '100 150 250' } }); fireEvent.blur(quick); expect(screen.getByLabelText('3. paket türü')).toBeTruthy(); expect(screen.getByText(/Son kalan:/).textContent).toContain('0'); });
  it('paket toplamı kalanı aşınca kaydetmeyi devre dışı bırakır', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); fireEvent.change(await screen.findByLabelText('Adet'), { target: { value: '501' } }); expect(screen.getByRole('button', { name: 'Paketleri kaydet' }).hasAttribute('disabled')).toBe(true); });
  it('batch paketleri tek mutation ile kaydeder', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); fireEvent.click(await screen.findByRole('button', { name: 'Paketleri kaydet' })); await waitFor(() => expect(createPackages).toHaveBeenCalledWith(expect.objectContaining({ workOrderId: workOrder.id, packages: [expect.objectContaining({ quantity: 250 })] }))); });
  it('teslim edilmemiş paketi düzenler', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); fireEvent.click((await screen.findAllByLabelText('Düzenle: Çuval #1'))[0]!); const quantityInput = screen.getByLabelText<HTMLInputElement>('Adet', { selector: '#edit-package-quantity' }); fireEvent.change(quantityInput, { target: { value: '200' } }); fireEvent.click(screen.getByRole('button', { name: 'Kaydet' })); await waitFor(() => expect(updatePackage).toHaveBeenCalled()); expect(updatePackage.mock.calls[0]?.[0].input.quantity).toBe(200); });
  it('paket silerken onay ister', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); fireEvent.click(await screen.findAllByLabelText('Sil: Çuval #1').then((items) => items[0]!)); await waitFor(() => expect(confirm).toHaveBeenCalled()); expect(deletePackage).toHaveBeenCalled(); });
  it('teslim edilmiş paket aksiyonlarını devre dışı bırakır', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); expect((await screen.findByLabelText('Düzenle: Koli #2')).hasAttribute('disabled')).toBe(true); expect(screen.getAllByText('Teslim Edildi').length).toBeGreaterThan(0); });
  it('masaüstü tablo ve mobil paket kart içeriğini birlikte render eder', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); expect(await screen.findByRole('table')).toBeTruthy(); expect(screen.getAllByText('Kırmızı bağ').length).toBeGreaterThan(0); expect(screen.getAllByText('Çuval #1').length).toBeGreaterThan(1); });
  it('teslimat paket seçimi canlı toplamı hesaplar ve teslimatı oluşturur', async () => { render(<OperationPage />, { wrapper: Providers }); selectWorkOrder(); fireEvent.click(await screen.findByRole('button', { name: 'Yeni teslimat' })); fireEvent.click(screen.getByRole('checkbox')); expect(screen.getByText('1 paket')).toBeTruthy(); expect(screen.getByText(/250 adet seçildi/)).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Teslimatı oluştur' })); await waitFor(() => expect(createDelivery).toHaveBeenCalledWith(expect.objectContaining({ workOrderId: workOrder.id, packageIds: ['package-1'] }))); });
  it('teslimat listesini masaüstü ve mobil içerikle gösterir', () => { render(<OperationPage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Teslimatlar' })); expect(screen.getByRole('table')).toBeTruthy(); expect(screen.getAllByText('Ahmet Yılmaz').length).toBeGreaterThan(0); expect(screen.getAllByText('250 adet').length).toBeGreaterThan(0); });
  it('müşteri filtresini teslimat sorgusuna taşır', async () => { render(<OperationPage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Teslimatlar' })); const box = screen.getByRole('combobox', { name: 'Teslimat müşteri filtresi' }); fireEvent.focus(box); fireEvent.click(screen.getByRole('option', { name: 'Alpha Tekstil' })); await waitFor(() => expect(useDeliveryList).toHaveBeenLastCalledWith(expect.objectContaining({ customerId: 'customer-1', page: 1 }))); });
  it('teslimat sayfa sayısı küçülünce son geçerli sayfaya döner', async () => { let totalPages = 2; vi.mocked(useDeliveryList).mockImplementation((params) => query({ items: [delivery], pagination: { page: params.page, pageSize: 20, total: totalPages === 2 ? 21 : 1, totalPages } }) as unknown as ReturnType<typeof useDeliveryList>); const { rerender } = render(<OperationPage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Teslimatlar' })); fireEvent.click(screen.getByLabelText('Sonraki sayfa')); await waitFor(() => expect(useDeliveryList).toHaveBeenLastCalledWith(expect.objectContaining({ page: 2 }))); totalPages = 1; rerender(<OperationPage />); await waitFor(() => expect(useDeliveryList).toHaveBeenLastCalledWith(expect.objectContaining({ page: 1 }))); });
  it('teslimat detayını ve paket geçmişini açar', async () => { render(<OperationPage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Teslimatlar' })); fireEvent.click(screen.getByLabelText('Detay: Galatasaray Garson')); expect((await screen.findAllByRole('heading', { name: 'Galatasaray Garson' })).length).toBeGreaterThan(0); expect(screen.getByText('Koli #2')).toBeTruthy(); });
  it('teslimat iptalinde confirmation kullanır', async () => { render(<OperationPage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Teslimatlar' })); fireEvent.click(screen.getByLabelText('Detay: Galatasaray Garson')); fireEvent.click(await screen.findByRole('button', { name: 'Teslimatı iptal et' })); await waitFor(() => expect(confirm).toHaveBeenCalled()); expect(cancelDelivery).toHaveBeenCalledWith(delivery.id); });
  it('teslimat loading, empty ve error durumlarını gösterir', () => { vi.mocked(useDeliveryList).mockReturnValue(query(undefined, { isPending: true }) as unknown as ReturnType<typeof useDeliveryList>); const { rerender } = render(<OperationPage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Teslimatlar' })); expect(screen.getByLabelText('Teslimatlar yükleniyor')).toBeTruthy(); vi.mocked(useDeliveryList).mockReturnValue(query({ items: [], pagination: { page: 1, pageSize: 20, total: 0, totalPages: 0 } }) as unknown as ReturnType<typeof useDeliveryList>); rerender(<OperationPage />); expect(screen.getByText('Henüz teslimat yok')).toBeTruthy(); vi.mocked(useDeliveryList).mockReturnValue(query(undefined, { isError: true }) as unknown as ReturnType<typeof useDeliveryList>); rerender(<OperationPage />); expect(screen.getByText('Teslimatlar yüklenemedi')).toBeTruthy(); });
});
