import { LoaderCircle, X } from 'lucide-react';
import { useState } from 'react';
import { Select } from '../../components/ui/select';
import { packageTypeLabels, packageTypes, type PackageInput, type PackageType, type WorkOrderPackage } from './operation.types';

export function PackageEditDialog({ item, pending, onClose, onSubmit }: { item: WorkOrderPackage; pending: boolean; onClose: () => void; onSubmit: (input: Partial<PackageInput>) => Promise<void> }) {
  const [type, setType] = useState<PackageType>(item.type); const [quantity, setQuantity] = useState(item.quantity); const [notes, setNotes] = useState(item.notes ?? '');
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/65 p-4"><section role="dialog" aria-modal="true" aria-labelledby="package-edit-title" tabIndex={-1} autoFocus onKeyDown={(e) => e.key === 'Escape' && !pending && onClose()} className="w-full max-w-lg rounded-xl border border-[var(--zeva-border-strong)] bg-[var(--zeva-surface)] p-5 shadow-2xl"><header className="flex justify-between"><div><p className="text-xs uppercase tracking-wider text-[var(--zeva-accent)]">Paket kaydı</p><h2 id="package-edit-title" className="mt-1 text-lg font-semibold text-white">{packageTypeLabels[item.type]} #{item.sequenceNo} düzenle</h2></div><button type="button" aria-label="Pencereyi kapat" onClick={onClose} className="grid size-9 place-items-center rounded-lg text-[#929b94]"><X className="size-5" /></button></header><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="text-sm text-[#d8ded9]">Tür</label><Select value={type} options={packageTypes.map((value) => ({ value, label: packageTypeLabels[value] }))} onChange={setType} ariaLabel="Paket türü" className="mt-1.5" /></div><div><label htmlFor="edit-package-quantity" className="text-sm text-[#d8ded9]">Adet</label><input id="edit-package-quantity" type="number" min={1} value={quantity} onChange={(e) => setQuantity(Number(e.target.value))} className="mt-1.5 min-h-11 w-full rounded-lg border border-[var(--zeva-border-strong)] bg-[#111512] px-3 text-white" /></div></div><div className="mt-4"><label htmlFor="edit-package-notes" className="text-sm text-[#d8ded9]">Not</label><textarea id="edit-package-notes" rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} className="mt-1.5 w-full rounded-lg border border-[var(--zeva-border-strong)] bg-[#111512] p-3 text-sm text-white" /></div><footer className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="min-h-10 rounded-lg border border-[var(--zeva-border-strong)] px-4 text-sm text-[#cbd2cc]">Vazgeç</button><button type="button" disabled={pending || !Number.isInteger(quantity) || quantity < 1} onClick={() => void onSubmit({ type, quantity, notes: notes.trim() || null })} className="flex min-h-10 items-center gap-2 rounded-lg bg-[var(--zeva-accent)] px-4 text-sm font-semibold text-[#0d140f] disabled:opacity-50">{pending ? <LoaderCircle className="size-4 animate-spin" /> : null} Kaydet</button></footer></section></div>;
}
