import type { FastifyPluginCallback } from 'fastify';

import { errorResponseSchema } from '../auth/auth.schema.js';
import { createFinanceController } from './finance.controller.js';
import { financeService, type FinanceService } from './finance.service.js';
import { adjustmentTypes, balanceStatuses, paymentMethods, statementTypes } from './finance.types.js';

export interface FinanceRoutesOptions { service?: FinanceService }

const security = [{ cookieAuth: [] }];
const idParams = (name: string) => ({ type: 'object', additionalProperties: false, required: [name], properties: { [name]: { type: 'string', minLength: 1, maxLength: 30 } } }) as const;
const pagination = { type: 'object', additionalProperties: false, required: ['page', 'pageSize', 'total', 'totalPages'], properties: { page: { type: 'integer' }, pageSize: { type: 'integer' }, total: { type: 'integer' }, totalPages: { type: 'integer' } } } as const;
const customer = { type: 'object', additionalProperties: false, required: ['id', 'name'], properties: { id: { type: 'string' }, name: { type: 'string' } } } as const;
const money = { type: 'string', pattern: '^-?(?:0|[1-9][0-9]{0,15})[.][0-9]{2}$' } as const;
const nullableDate = { type: ['string', 'null'], format: 'date-time' } as const;
const success = (data: Record<string, unknown>) => ({ type: 'object', additionalProperties: false, required: ['success', 'data'], properties: { success: { type: 'boolean', const: true }, data } }) as const;
const payment = {
  type: 'object', additionalProperties: false,
  required: ['id', 'customer', 'amount', 'method', 'paidAt', 'referenceNo', 'notes', 'cancelledAt', 'createdAt', 'updatedAt'],
  properties: { id: { type: 'string' }, customer, amount: money, method: { type: 'string', enum: paymentMethods }, paidAt: { type: 'string', format: 'date-time' }, referenceNo: { type: ['string', 'null'] }, notes: { type: ['string', 'null'] }, cancelledAt: nullableDate, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } },
} as const;
const adjustment = {
  type: 'object', additionalProperties: false,
  required: ['id', 'customer', 'type', 'amount', 'occurredAt', 'description', 'cancelledAt', 'createdAt', 'updatedAt'],
  properties: { id: { type: 'string' }, customer, type: { type: 'string', enum: adjustmentTypes }, amount: money, occurredAt: { type: 'string', format: 'date-time' }, description: { type: 'string' }, cancelledAt: nullableDate, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } },
} as const;
const summary = { type: 'object', additionalProperties: false, required: ['workOrderTotal', 'debitAdjustments', 'paymentsTotal', 'creditAdjustments', 'balance'], properties: { workOrderTotal: money, debitAdjustments: money, paymentsTotal: money, creditAdjustments: money, balance: money } } as const;
const listQuery = { type: 'object', additionalProperties: false, properties: { q: { type: 'string', maxLength: 191 }, page: { type: 'integer', minimum: 1, default: 1 }, pageSize: { type: 'integer', minimum: 1, maximum: 100, default: 20 }, customerId: { type: 'string', maxLength: 30 }, method: { type: 'string', enum: paymentMethods }, paidFrom: { type: 'string', format: 'date-time' }, paidTo: { type: 'string', format: 'date-time' }, cancelled: { type: 'boolean' } } } as const;

export const financeRoutes: FastifyPluginCallback<FinanceRoutesOptions> = (app, options, done) => {
  const controller = createFinanceController(options.service ?? financeService);
  app.addHook('preHandler', (request) => app.authenticate(request));

  app.get('/customer-accounts', { schema: { operationId: 'listCustomerAccounts', summary: 'Müşteri cari hesaplarını listeler', tags: ['Finance'], security, querystring: { type: 'object', additionalProperties: false, properties: { q: { type: 'string', maxLength: 191 }, page: { type: 'integer', minimum: 1, default: 1 }, pageSize: { type: 'integer', minimum: 1, maximum: 100, default: 20 }, balanceStatus: { type: 'string', enum: balanceStatuses } } }, response: { 200: success({ type: 'object', additionalProperties: false, required: ['items', 'overview', 'pagination'], properties: { items: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['customer', 'summary', 'lastPaymentAt', 'lastActivityAt'], properties: { customer, summary, lastPaymentAt: nullableDate, lastActivityAt: nullableDate } } }, overview: { type: 'object', additionalProperties: false, required: ['totalReceivable', 'totalCustomerCredit', 'openAccountCount', 'monthPayments'], properties: { totalReceivable: money, totalCustomerCredit: money, openAccountCount: { type: 'integer' }, monthPayments: money } }, pagination } }), 400: errorResponseSchema, 401: errorResponseSchema } }, handler: controller.listAccounts });
  app.get('/customer-accounts/:customerId', { schema: { operationId: 'getCustomerAccount', summary: 'Müşteri cari hesabını ve hareketlerini getirir', tags: ['Finance'], security, params: idParams('customerId'), querystring: { type: 'object', additionalProperties: false, properties: { page: { type: 'integer', minimum: 1, default: 1 }, pageSize: { type: 'integer', minimum: 1, maximum: 100, default: 20 }, from: { type: 'string', format: 'date-time' }, to: { type: 'string', format: 'date-time' }, type: { type: 'string', enum: statementTypes } } }, response: { 200: success({ type: 'object', additionalProperties: false, required: ['customer', 'summary', 'statement'], properties: { customer, summary: { ...summary, required: [...summary.required, 'lastPaymentAt'], properties: { ...summary.properties, lastPaymentAt: nullableDate } }, statement: { type: 'object', additionalProperties: false, required: ['items', 'pagination'], properties: { items: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['id', 'sourceId', 'type', 'occurredAt', 'description', 'debit', 'credit', 'cancelledAt'], properties: { id: { type: 'string' }, sourceId: { type: 'string' }, type: { type: 'string', enum: statementTypes }, occurredAt: { type: 'string', format: 'date-time' }, description: { type: 'string' }, debit: money, credit: money, cancelledAt: nullableDate } } }, pagination } } } }), 400: errorResponseSchema, 401: errorResponseSchema, 404: errorResponseSchema } }, handler: controller.getAccount });

  app.get('/payments', { schema: { operationId: 'listPayments', summary: 'Tahsilat kayıtlarını listeler', tags: ['Payments'], security, querystring: listQuery, response: { 200: success({ type: 'object', additionalProperties: false, required: ['items', 'pagination'], properties: { items: { type: 'array', items: payment }, pagination } }), 400: errorResponseSchema, 401: errorResponseSchema } }, handler: controller.listPayments });
  app.post('/payments', { schema: { operationId: 'createPayment', summary: 'Yeni tahsilat kaydeder', tags: ['Payments'], security, body: { type: 'object', additionalProperties: false, required: ['customerId', 'amount', 'method', 'paidAt'], properties: { customerId: { type: 'string', maxLength: 30 }, amount: { type: 'string', pattern: '^(?:0|[1-9][0-9]{0,15})(?:[.][0-9]{1,2})?$' }, method: { type: 'string', enum: paymentMethods }, paidAt: { type: 'string', format: 'date-time' }, referenceNo: { type: ['string', 'null'], maxLength: 120 }, notes: { type: ['string', 'null'], maxLength: 5000 } } }, response: { 201: success({ type: 'object', additionalProperties: false, required: ['payment'], properties: { payment } }), 400: errorResponseSchema, 401: errorResponseSchema, 404: errorResponseSchema } }, handler: controller.createPayment });
  app.get('/payments/:id', { schema: { operationId: 'getPayment', summary: 'Tahsilat detayını getirir', tags: ['Payments'], security, params: idParams('id'), response: { 200: success({ type: 'object', additionalProperties: false, required: ['payment'], properties: { payment } }), 400: errorResponseSchema, 401: errorResponseSchema, 404: errorResponseSchema } }, handler: controller.getPayment });
  app.post('/payments/:id/cancel', { schema: { operationId: 'cancelPayment', summary: 'Tahsilat kaydını iptal eder', tags: ['Payments'], security, params: idParams('id'), response: { 200: success({ type: 'object', additionalProperties: false, required: ['payment'], properties: { payment } }), 400: errorResponseSchema, 401: errorResponseSchema, 404: errorResponseSchema, 409: errorResponseSchema } }, handler: controller.cancelPayment });

  app.post('/account-adjustments', { schema: { operationId: 'createAccountAdjustment', summary: 'Cari hesaba manuel düzeltme ekler', tags: ['Finance'], security, body: { type: 'object', additionalProperties: false, required: ['customerId', 'type', 'amount', 'occurredAt', 'description'], properties: { customerId: { type: 'string', maxLength: 30 }, type: { type: 'string', enum: adjustmentTypes }, amount: { type: 'string', pattern: '^(?:0|[1-9][0-9]{0,15})(?:[.][0-9]{1,2})?$' }, occurredAt: { type: 'string', format: 'date-time' }, description: { type: 'string', minLength: 3, maxLength: 500 } } }, response: { 201: success({ type: 'object', additionalProperties: false, required: ['adjustment'], properties: { adjustment } }), 400: errorResponseSchema, 401: errorResponseSchema, 404: errorResponseSchema } }, handler: controller.createAdjustment });
  app.post('/account-adjustments/:id/cancel', { schema: { operationId: 'cancelAccountAdjustment', summary: 'Cari düzeltmeyi iptal eder', tags: ['Finance'], security, params: idParams('id'), response: { 200: success({ type: 'object', additionalProperties: false }), 400: errorResponseSchema, 401: errorResponseSchema, 404: errorResponseSchema, 409: errorResponseSchema } }, handler: controller.cancelAdjustment });
  done();
};
