import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import type { PropsWithChildren } from 'react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ConfirmationContext, type ConfirmationContextValue } from '../../contexts/confirmation-context';
import { ToastContext, type ToastContextValue } from '../../contexts/toast-context';
import { useCustomerList } from '../customers/customer.queries';
import { FinancePage } from './finance-page';
import { useAccountDetail, useAccountList, useCancelAdjustment, useCancelPayment, useCreateAdjustment, useCreatePayment, usePaymentDetail, usePaymentList } from './finance.queries';
import type { AccountDetail, AccountListData, Payment } from './finance.types';

vi.mock('../customers/customer.queries', () => ({ useCustomerList: vi.fn() }));
vi.mock('./finance.queries', () => ({ useAccountList: vi.fn(), useAccountDetail: vi.fn(), usePaymentList: vi.fn(), usePaymentDetail: vi.fn(), useCreatePayment: vi.fn(), useCancelPayment: vi.fn(), useCreateAdjustment: vi.fn(), useCancelAdjustment: vi.fn() }));
const customer = { id: 'customer-1', name: 'Alpha Tekstil' };
const accountDetail: AccountDetail = { customer, summary: { workOrderTotal: '5000.00', debitAdjustments: '500.00', paymentsTotal: '2000.00', creditAdjustments: '250.00', balance: '3250.00', lastPaymentAt: '2026-08-12T10:00:00.000Z' }, statement: { items: [{ id: 'wo:1', sourceId: 'wo-1', type: 'WORK_ORDER', occurredAt: '2026-08-12T10:00:00.000Z', description: 'İş Emri · Galatasaray Garson', debit: '1250.00', credit: '0.00', cancelledAt: null }, { id: 'pay:1', sourceId: 'payment-1', type: 'PAYMENT', occurredAt: '2026-08-11T10:00:00.000Z', description: 'Tahsilat · BANK_TRANSFER', debit: '0.00', credit: '500.00', cancelledAt: null }, { id: 'adj:1', sourceId: 'adjustment-1', type: 'ADJUSTMENT_DEBIT', occurredAt: '2026-08-10T10:00:00.000Z', description: 'Açılış bakiyesi', debit: '300.00', credit: '0.00', cancelledAt: null }], pagination: { page: 1, pageSize: 20, total: 3, totalPages: 1 } } };
const accounts: AccountListData = { items: [{ customer, summary: accountDetail.summary, lastPaymentAt: accountDetail.summary.lastPaymentAt, lastActivityAt: '2026-08-12T10:00:00.000Z' }, { customer: { id: 'credit', name: 'Beta Giyim' }, summary: { workOrderTotal: '0.00', debitAdjustments: '0.00', paymentsTotal: '1500.00', creditAdjustments: '0.00', balance: '-1500.00' }, lastPaymentAt: null, lastActivityAt: null }, { customer: { id: 'settled', name: 'Gamma Tekstil' }, summary: { workOrderTotal: '100.00', debitAdjustments: '0.00', paymentsTotal: '100.00', creditAdjustments: '0.00', balance: '0.00' }, lastPaymentAt: null, lastActivityAt: null }], overview: { totalReceivable: '3250.00', totalCustomerCredit: '1500.00', openAccountCount: 2, monthPayments: '2100.00' }, pagination: { page: 1, pageSize: 20, total: 3, totalPages: 1 } };
const payment: Payment = { id: 'payment-1', customerId: customer.id, customer, amount: '500.00', method: 'BANK_TRANSFER', paidAt: '2026-08-12T10:00:00.000Z', referenceNo: 'EFT-42', notes: 'İlk tahsilat', cancelledAt: null, createdAt: '2026-08-12T10:00:00.000Z', updatedAt: '2026-08-12T10:00:00.000Z' };
const result = <T,>(data: T | undefined, extra: Record<string, unknown> = {}) => ({ data, isPending: false, isError: false, isFetching: false, isPlaceholderData: false, refetch: vi.fn(), ...extra });
const confirm = vi.fn<ConfirmationContextValue['confirm']>(); const toast: ToastContextValue = { show: vi.fn(() => 'id'), success: vi.fn(() => 'id'), error: vi.fn(() => 'id'), warning: vi.fn(() => 'id'), info: vi.fn(() => 'id'), dismiss: vi.fn() };
const createPayment = vi.fn().mockResolvedValue(payment); const cancelPayment = vi.fn().mockResolvedValue({ ...payment, cancelledAt: payment.updatedAt }); const createAdjustment = vi.fn().mockResolvedValue({}); const cancelAdjustment = vi.fn().mockResolvedValue({});
function Providers({ children }: PropsWithChildren) { return <MemoryRouter><ToastContext.Provider value={toast}><ConfirmationContext.Provider value={{ confirm }}>{children}</ConfirmationContext.Provider></ToastContext.Provider></MemoryRouter>; }
function configure() { vi.mocked(useAccountList).mockReturnValue(result(accounts) as unknown as ReturnType<typeof useAccountList>); vi.mocked(useAccountDetail).mockReturnValue(result(accountDetail) as unknown as ReturnType<typeof useAccountDetail>); vi.mocked(usePaymentList).mockReturnValue(result({ items: [payment], pagination: { page: 1, pageSize: 20, total: 1, totalPages: 1 } }) as unknown as ReturnType<typeof usePaymentList>); vi.mocked(usePaymentDetail).mockReturnValue(result(payment) as unknown as ReturnType<typeof usePaymentDetail>); vi.mocked(useCustomerList).mockReturnValue(result({ items: [{ ...customer, contactName: null, phone: null, address: null, notes: null, createdAt: payment.createdAt, updatedAt: payment.updatedAt, deletedAt: null }], pagination: { page: 1, pageSize: 20, total: 1, totalPages: 1 } }) as unknown as ReturnType<typeof useCustomerList>); vi.mocked(useCreatePayment).mockReturnValue({ mutateAsync: createPayment, isPending: false } as unknown as ReturnType<typeof useCreatePayment>); vi.mocked(useCancelPayment).mockReturnValue({ mutateAsync: cancelPayment, isPending: false } as unknown as ReturnType<typeof useCancelPayment>); vi.mocked(useCreateAdjustment).mockReturnValue({ mutateAsync: createAdjustment, isPending: false } as unknown as ReturnType<typeof useCreateAdjustment>); vi.mocked(useCancelAdjustment).mockReturnValue({ mutateAsync: cancelAdjustment, isPending: false } as unknown as ReturnType<typeof useCancelAdjustment>); }
describe('FinancePage', () => {
  beforeEach(() => { vi.clearAllMocks(); confirm.mockResolvedValue(true); configure(); });
  it('Cari Hesaplar sekmesini özetler ve pozitif, negatif, kapalı bakiye dilini gösterir', () => { render(<FinancePage />, { wrapper: Providers }); expect(screen.getByRole('tab', { name: 'Cari Hesaplar' })).toBeTruthy(); expect(screen.getAllByText('3.250,00 TL alınacak').length).toBeGreaterThan(0); expect(screen.getAllByText('1.500,00 TL müşteri alacağı').length).toBeGreaterThan(0); expect(screen.getAllByText('Hesap kapalı').length).toBeGreaterThan(0); expect(screen.getByText('2.100,00 TL')).toBeTruthy(); });
  it('müşteri aramasını debounce eder ve bakiye filtresini sorguya taşır', async () => { render(<FinancePage />, { wrapper: Providers }); fireEvent.change(screen.getByLabelText('Müşteri ara'), { target: { value: 'Alpha' } }); await waitFor(() => expect(useAccountList).toHaveBeenLastCalledWith(expect.objectContaining({ q: 'Alpha', page: 1 }))); fireEvent.click(screen.getByRole('button', { name: 'Bakiye durumu' })); fireEvent.click(screen.getByRole('option', { name: 'Müşteri alacağı' })); expect(useAccountList).toHaveBeenLastCalledWith(expect.objectContaining({ balanceStatus: 'CREDIT' })); });
  it('cari detayında tüm hareket türlerini, tutarları ve PDF aksiyonunu gösterir', async () => { render(<FinancePage />, { wrapper: Providers }); fireEvent.click(screen.getAllByLabelText('Cari hesabı görüntüle: Alpha Tekstil')[0]!); expect(await screen.findByText('Cari hareketler')).toBeTruthy(); expect(screen.getByText('İş Emri · Galatasaray Garson')).toBeTruthy(); expect(screen.getByText('Açılış bakiyesi')).toBeTruthy(); expect(screen.getAllByText('Tahsilat').length).toBeGreaterThan(0); expect(screen.getByText('+1.250,00 TL')).toBeTruthy(); expect(screen.getByRole('button', { name: 'Cari Ekstre İndir' })).toBeTruthy(); });
  it('tahsilat formunda müşteri combobox ve custom ödeme yöntemi ile kayıt oluşturur', async () => { render(<FinancePage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('button', { name: 'Yeni Tahsilat' })); const box = screen.getByRole('combobox', { name: 'Tahsilat müşterisi' }); fireEvent.change(box, { target: { value: 'Alpha' } }); fireEvent.click(await screen.findByRole('option', { name: 'Alpha Tekstil' })); fireEvent.change(screen.getByPlaceholderText('0,00'), { target: { value: '600,50' } }); fireEvent.click(screen.getByRole('button', { name: 'Ödeme yöntemi' })); fireEvent.click(screen.getByRole('option', { name: 'Havale / EFT' })); fireEvent.click(screen.getByRole('button', { name: 'Tahsilatı kaydet' })); await waitFor(() => expect(createPayment).toHaveBeenCalledWith(expect.objectContaining({ customerId: customer.id, amount: '600.50', method: 'BANK_TRANSFER' }))); });
  it('fazla tahsilatı UI seviyesinde engellemez ve açıklayıcı bilgi gösterir', () => { render(<FinancePage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('button', { name: 'Yeni Tahsilat' })); expect(screen.getByText(/Fazla tutar müşterinin alacağı/)).toBeTruthy(); expect(screen.getByRole('button', { name: 'Tahsilatı kaydet' }).hasAttribute('disabled')).toBe(false); });
  it('tahsilat listesini masaüstü tablo ve mobil kart olarak render eder', () => { render(<FinancePage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Tahsilatlar' })); expect(screen.getByRole('table')).toBeTruthy(); expect(screen.getAllByText('500,00 TL').length).toBeGreaterThan(0); expect(screen.getAllByText('Havale / EFT').length).toBeGreaterThan(0); });
  it('tahsilat müşteri ve yöntem filtrelerini query parametrelerine taşır', async () => { render(<FinancePage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Tahsilatlar' })); const customerFilter = screen.getByRole('combobox', { name: 'Tahsilat müşteri filtresi' }); fireEvent.focus(customerFilter); fireEvent.click(screen.getByRole('option', { name: 'Alpha Tekstil' })); fireEvent.click(screen.getByRole('button', { name: 'Ödeme yöntemi filtresi' })); fireEvent.click(screen.getByRole('option', { name: 'Nakit' })); await waitFor(() => expect(usePaymentList).toHaveBeenLastCalledWith(expect.objectContaining({ customerId: customer.id, method: 'CASH' }))); });
  it('tahsilat detayını gösterir ve iptalde confirmation kullanır', async () => { render(<FinancePage />, { wrapper: Providers }); fireEvent.click(screen.getByRole('tab', { name: 'Tahsilatlar' })); fireEvent.click(screen.getAllByLabelText('Tahsilatı görüntüle: Alpha Tekstil')[0]!); expect(await screen.findByText('İlk tahsilat')).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Kaydı İptal Et' })); await waitFor(() => expect(confirm).toHaveBeenCalled()); expect(cancelPayment).toHaveBeenCalledWith(payment.id); });
  it('cari düzeltme oluşturur ve düzeltme iptalinde onay ister', async () => { render(<FinancePage />, { wrapper: Providers }); fireEvent.click(screen.getAllByLabelText('Cari hesabı görüntüle: Alpha Tekstil')[0]!); fireEvent.click(await screen.findByRole('button', { name: 'Cari Düzeltme' })); fireEvent.change(screen.getByPlaceholderText('0,00'), { target: { value: '300' } }); fireEvent.change(screen.getByPlaceholderText('Örn. 2026 öncesi açılış bakiyesi'), { target: { value: 'Eski bakiye' } }); fireEvent.click(screen.getByRole('button', { name: 'Düzeltmeyi kaydet' })); await waitFor(() => expect(createAdjustment).toHaveBeenCalledWith(expect.objectContaining({ amount: '300.00', type: 'DEBIT' }))); fireEvent.click(screen.getByLabelText('Cari düzeltmeyi iptal et: Açılış bakiyesi')); await waitFor(() => expect(confirm).toHaveBeenCalled()); expect(cancelAdjustment).toHaveBeenCalledWith('adjustment-1'); });
  it('loading, empty ve error durumlarını açıkça gösterir', () => { vi.mocked(useAccountList).mockReturnValue(result(undefined, { isPending: true }) as unknown as ReturnType<typeof useAccountList>); const { rerender } = render(<FinancePage />, { wrapper: Providers }); expect(screen.getByLabelText('Cari hesaplar yükleniyor')).toBeTruthy(); vi.mocked(useAccountList).mockReturnValue(result({ ...accounts, items: [], pagination: { ...accounts.pagination, total: 0, totalPages: 0 } }) as unknown as ReturnType<typeof useAccountList>); rerender(<FinancePage />); expect(screen.getByText('Cari hesap bulunamadı')).toBeTruthy(); vi.mocked(useAccountList).mockReturnValue(result(undefined, { isError: true }) as unknown as ReturnType<typeof useAccountList>); rerender(<FinancePage />); expect(screen.getByText('Cari hesaplar yüklenemedi')).toBeTruthy(); });
});
