import { Select } from '../../components/ui/select';
import { createCustomDateFilter, createDateFilter, type DateFilterValue, type DatePreset } from './date-range';

const options = [{ value: 'TODAY', label: 'Bugün' }, { value: 'LAST_7_DAYS', label: 'Son 7 Gün' }, { value: 'THIS_MONTH', label: 'Bu Ay' }, { value: 'LAST_MONTH', label: 'Geçen Ay' }, { value: 'LAST_30_DAYS', label: 'Son 30 Gün' }, { value: 'THIS_YEAR', label: 'Bu Yıl' }, { value: 'CUSTOM', label: 'Özel Aralık' }] as const;

export function DateRangeFilter({ value, onChange }: { value: DateFilterValue; onChange: (value: DateFilterValue) => void }) {
  const custom = (fromDate: string, toDate: string) => onChange(createCustomDateFilter(fromDate, toDate));
  return <section aria-label="Dönem filtresi" className="grid gap-3 rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)] p-4 sm:grid-cols-[220px_1fr_1fr] sm:items-end"><div><label className="mb-1.5 block text-xs text-[var(--zeva-text-muted)]">Dönem</label><Select<DatePreset> ariaLabel="Dönem" value={value.preset} options={[...options]} onChange={(preset) => onChange(preset === 'CUSTOM' ? { ...value, preset } : createDateFilter(preset))} /></div><label className="text-xs text-[var(--zeva-text-muted)]">Başlangıç<input aria-label="Başlangıç tarihi" type="date" value={value.fromDate} onChange={(event) => custom(event.target.value, value.toDate)} className="mt-1.5 min-h-11 w-full rounded-lg border border-[var(--zeva-border-strong)] bg-[#111512] px-3 text-sm text-white" /></label><label className="text-xs text-[var(--zeva-text-muted)]">Bitiş<input aria-label="Bitiş tarihi" type="date" value={value.toDate} onChange={(event) => custom(value.fromDate, event.target.value)} className="mt-1.5 min-h-11 w-full rounded-lg border border-[var(--zeva-border-strong)] bg-[#111512] px-3 text-sm text-white" /></label></section>;
}
