import type { WorkOrderStatus, WorkOrderType } from '../work-orders/work-order.types';
export interface Pagination { page: number; pageSize: number; total: number; totalPages: number }
export interface CustomerSummary { id: string; name: string }
export interface DateRange { from: string; to: string }
export interface DashboardData { kpis: { activeWorkOrders: number; readyForDelivery: number; deliveredQuantityThisMonth: number; totalReceivable: string }; metrics: { activeCustomerCount: number; waitingWorkOrders: number; inProgressWorkOrders: number; packagedNotFullyDeliveredWorkOrders: number; monthPayments: string; overdueWorkOrders: number }; workOrderStatuses: Array<{ status: WorkOrderStatus; count: number }>; overdueWorkOrders: Array<{ id: string; customer: CustomerSummary; productName: string; status: WorkOrderStatus; dueAt: string; overdueDays: number }>; recentActivity: Array<{ id: string; sourceId: string; type: 'WORK_ORDER' | 'DELIVERY' | 'PAYMENT'; occurredAt: string; title: string; description: string }> }
export interface WorkOrderReportParams extends DateRange { page: number; pageSize: number; customerId: string; type: WorkOrderType | ''; status: WorkOrderStatus | '' }
export interface WorkOrderReportData { summary: { totalWorkOrders: number; totalQuantity: number; totalAmount: string }; statusDistribution: Array<{ status: WorkOrderStatus; count: number }>; typeDistribution: Array<{ type: WorkOrderType; count: number }>; customerSummary: Array<{ customer: CustomerSummary; workOrderCount: number; totalQuantity: number; totalAmount: string }>; items: Array<{ id: string; customer: CustomerSummary; productName: string; type: WorkOrderType; status: WorkOrderStatus; totalQuantity: number; totalAmount: string; receivedAt: string }>; pagination: Pagination }
export interface DeliveryReportParams extends DateRange { page: number; pageSize: number; customerId: string; workOrderId: string }
export interface DeliveryReportData { summary: { totalDeliveries: number; totalPackages: number; totalQuantity: number }; customerSummary: Array<{ customer: CustomerSummary; deliveryCount: number; totalQuantity: number }>; items: Array<{ id: string; customer: CustomerSummary; deliveredAt: string; workOrderCount: number; packageCount: number; totalQuantity: number; receiverName: string | null; cancelledAt: string | null }>; pagination: Pagination }
export interface FinanceReportData { period: { workOrderTotal: string; paymentsTotal: string; debitAdjustments: string; creditAdjustments: string }; current: { totalReceivable: string; totalCustomerCredit: string } }
export interface CustomerReportParams extends DateRange { page: number; pageSize: number; q: string }
export interface CustomerReportData { items: Array<{ customer: CustomerSummary; workOrderCount: number; totalQuantity: number; workOrderTotal: string; paymentsTotal: string; debitAdjustments: string; creditAdjustments: string; balance: string; lastWorkOrderAt: string | null; lastPaymentAt: string | null }>; pagination: Pagination }
