import { ChevronLeft, ChevronRight, ClipboardList, RefreshCw, Truck, UsersRound } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { useMemo, useState } from 'react';
import { EmptyState } from '../../components/feedback/empty-state';
import { Skeleton } from '../../components/feedback/skeleton';
import { Combobox } from '../../components/ui/combobox';
import { Select } from '../../components/ui/select';
import { formatBalance, formatMoney } from '../../lib/money';
import { useCustomerList } from '../customers/customer.queries';
import { workOrderTypeLabels, workOrderTypes } from '../customers/customer.types';
import { WorkOrderStatusBadge } from '../work-orders/work-order-status-badge';
import { workOrderStatuses, workOrderStatusLabels, type WorkOrderStatus, type WorkOrderType } from '../work-orders/work-order.types';
import { DateRangeFilter } from './date-range-filter';
import { createDateFilter, type DateFilterValue } from './date-range';
import { useCustomerReport, useDeliveryReport, useFinanceReport, useWorkOrderReport } from './reporting.queries';
import type { CustomerReportData, DeliveryReportData, WorkOrderReportData } from './reporting.types';

type Tab = 'work-orders' | 'deliveries' | 'finance' | 'customers';
const tabs: Array<{ value: Tab; label: string }> = [{ value: 'work-orders', label: 'İş Emirleri' }, { value: 'deliveries', label: 'Teslimatlar' }, { value: 'finance', label: 'Finans' }, { value: 'customers', label: 'Müşteriler' }];
const date = (value: string | null) => value ? new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium' }).format(new Date(value)) : '—';
export function ReportsPage() {
  const [tab, setTab] = useState<Tab>('work-orders'); const [range, setRange] = useState<DateFilterValue>(() => createDateFilter('THIS_MONTH')); const [page, setPage] = useState(1);
  const [customerSearch, setCustomerSearch] = useState(''); const [customerId, setCustomerId] = useState(''); const [customerLabel, setCustomerLabel] = useState(''); const [type, setType] = useState<WorkOrderType | ''>(''); const [status, setStatus] = useState<WorkOrderStatus | ''>(''); const [customerReportSearch, setCustomerReportSearch] = useState('');
  const customers = useCustomerList({ q: customerSearch, page: 1, pageSize: 20, deleted: false }); const base = useMemo(() => ({ from: range.from, to: range.to }), [range.from, range.to]);
  const workOrders = useWorkOrderReport({ ...base, page, pageSize: 20, customerId, type, status }, tab === 'work-orders');
  const deliveries = useDeliveryReport({ ...base, page, pageSize: 20, customerId, workOrderId: '' }, tab === 'deliveries');
  const finance = useFinanceReport(base, tab === 'finance'); const customerReport = useCustomerReport({ ...base, page, pageSize: 20, q: customerReportSearch }, tab === 'customers');
  const chooseTab = (value: Tab) => { setTab(value); setPage(1); }; const updateRange = (value: DateFilterValue) => { setRange(value); setPage(1); };
  const customerOptions = customers.data?.items.map((item) => ({ value: item.id, label: item.name })) ?? [];
  return <div className="space-y-5"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--zeva-accent)]">Analiz</p><h1 className="mt-1 text-2xl font-semibold text-white">Raporlar</h1><p className="mt-1.5 text-sm text-[var(--zeva-text-muted)]">Dönemsel üretim, teslimat, finans ve müşteri özetleri.</p></header><DateRangeFilter value={range} onChange={updateRange} /><div role="tablist" className="grid grid-cols-2 rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)] p-1 sm:inline-flex sm:grid-cols-none">{tabs.map((item) => <button key={item.value} role="tab" aria-selected={tab === item.value} onClick={() => chooseTab(item.value)} className={`min-h-10 rounded-lg px-4 text-sm ${tab === item.value ? 'bg-[#27342a] text-white' : 'text-[var(--zeva-text-muted)]'}`}>{item.label}</button>)}</div>
    {tab === 'work-orders' ? <><FilterPanel customerId={customerId} customerLabel={customerLabel} options={customerOptions} loading={customers.isFetching} onSearch={setCustomerSearch} onCustomer={(id) => { setCustomerId(id); setCustomerLabel(customerOptions.find((item) => item.value === id)?.label ?? ''); setPage(1); }} type={type} status={status} onType={(value) => { setType(value); setPage(1); }} onStatus={(value) => { setStatus(value); setPage(1); }} /><WorkOrdersView query={workOrders} page={page} onPage={setPage} /></> : null}
    {tab === 'deliveries' ? <><section className="rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)] p-4"><Combobox value={customerId} selectedLabel={customerLabel} options={customerOptions} onChange={(id) => { setCustomerId(id); setCustomerLabel(customerOptions.find((item) => item.value === id)?.label ?? ''); setPage(1); }} onSearchChange={setCustomerSearch} ariaLabel="Teslimat müşteri filtresi" placeholder="Müşteri ara…" clearOptionLabel="Tüm müşteriler" loading={customers.isFetching} className="max-w-md" /></section><DeliveriesView query={deliveries} page={page} onPage={setPage} /></> : null}
    {tab === 'finance' ? <FinanceView query={finance} /> : null}
    {tab === 'customers' ? <><section className="rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)] p-4"><label htmlFor="customer-report-search" className="sr-only">Müşteri ara</label><input id="customer-report-search" value={customerReportSearch} onChange={(event) => { setCustomerReportSearch(event.target.value); setPage(1); }} placeholder="Müşteri ara…" className="min-h-11 w-full max-w-md rounded-lg border border-[var(--zeva-border-strong)] bg-[#111512] px-3 text-sm text-white" /></section><CustomersView query={customerReport} page={page} onPage={setPage} /></> : null}
  </div>;
}
function FilterPanel(props: { customerId: string; customerLabel: string; options: Array<{ value: string; label: string }>; loading: boolean; onSearch: (value: string) => void; onCustomer: (value: string) => void; type: WorkOrderType | ''; status: WorkOrderStatus | ''; onType: (value: WorkOrderType | '') => void; onStatus: (value: WorkOrderStatus | '') => void }) { return <section className="grid gap-3 rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)] p-4 md:grid-cols-3"><Combobox value={props.customerId} selectedLabel={props.customerLabel} options={props.options} onChange={props.onCustomer} onSearchChange={props.onSearch} ariaLabel="İş emri müşteri filtresi" placeholder="Müşteri ara…" clearOptionLabel="Tüm müşteriler" loading={props.loading} /><Select<WorkOrderType | ''> ariaLabel="Hizmet türü" value={props.type} options={[{ value: '', label: 'Tüm hizmetler' }, ...workOrderTypes.map((value) => ({ value, label: workOrderTypeLabels[value] }))]} onChange={props.onType} /><Select<WorkOrderStatus | ''> ariaLabel="İş durumu" value={props.status} options={[{ value: '', label: 'Tüm aktif durumlar' }, ...workOrderStatuses.map((value) => ({ value, label: workOrderStatusLabels[value] }))]} onChange={props.onStatus} /></section>; }
function WorkOrdersView({ query, page, onPage }: { query: ReturnType<typeof useWorkOrderReport>; page: number; onPage: (value: number) => void }) { const data = query.data; if (query.isPending) return <Loading label="İş emri raporu yükleniyor" />; if (query.isError || !data) return <ReportError title="İş emri raporu yüklenemedi" />; return <div className="space-y-4"><SummaryGrid values={[['Toplam İş Emri', data.summary.totalWorkOrders], ['Toplam Adet', data.summary.totalQuantity.toLocaleString('tr-TR')], ['Toplam İş Tutarı', formatMoney(data.summary.totalAmount)]]} /><div className="grid gap-3 lg:grid-cols-3"><Breakdown title="Durum Dağılımı" values={data.statusDistribution.map((item) => [workOrderStatusLabels[item.status], item.count])} /><Breakdown title="Hizmet Dağılımı" values={data.typeDistribution.map((item) => [workOrderTypeLabels[item.type], item.count])} /><Breakdown title="Müşteri Özeti" values={data.customerSummary.map((item) => [item.customer.name, `${item.totalQuantity.toLocaleString('tr-TR')} adet · ${formatMoney(item.totalAmount)}`])} /></div>{data.items.length ? <><WorkOrderRows data={data} /><Pagination page={page} data={data.pagination} onPage={onPage} /></> : <ReportEmpty title="İş emri bulunamadı" icon={ClipboardList} />}</div>; }
function WorkOrderRows({ data }: { data: WorkOrderReportData }) { return <section className="overflow-hidden rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)]"><div className="hidden lg:block"><table className="w-full"><thead><tr className="border-b border-[var(--zeva-border)] text-left text-xs text-[var(--zeva-text-muted)]"><th className="px-4 py-3">Tarih</th><th>Müşteri</th><th>İş</th><th>Hizmet</th><th>Durum</th><th>Adet</th><th className="px-4">Tutar</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id} className="border-b border-[var(--zeva-border)] last:border-0"><td className="px-4 py-3">{date(item.receivedAt)}</td><td>{item.customer.name}</td><td className="font-medium text-white">{item.productName}</td><td>{workOrderTypeLabels[item.type]}</td><td><WorkOrderStatusBadge status={item.status} /></td><td>{item.totalQuantity.toLocaleString('tr-TR')}</td><td className="px-4 font-semibold text-white">{formatMoney(item.totalAmount)}</td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 lg:hidden">{data.items.map((item) => <article key={item.id} className="rounded-lg border border-[var(--zeva-border)] bg-[#111512] p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-white">{item.productName}</h3><p className="mt-1 text-xs text-[var(--zeva-text-muted)]">{item.customer.name} · {date(item.receivedAt)}</p></div><WorkOrderStatusBadge status={item.status} /></div><div className="mt-3 flex justify-between text-sm"><span>{item.totalQuantity.toLocaleString('tr-TR')} adet</span><strong>{formatMoney(item.totalAmount)}</strong></div></article>)}</div></section>; }
function DeliveriesView({ query, page, onPage }: { query: ReturnType<typeof useDeliveryReport>; page: number; onPage: (value: number) => void }) { const data = query.data; if (query.isPending) return <Loading label="Teslimat raporu yükleniyor" />; if (query.isError || !data) return <ReportError title="Teslimat raporu yüklenemedi" />; return <div className="space-y-4"><SummaryGrid values={[['Aktif Teslimat', data.summary.totalDeliveries], ['Teslim Edilen Paket', data.summary.totalPackages], ['Teslim Edilen Adet', data.summary.totalQuantity.toLocaleString('tr-TR')]]} /><Breakdown title="Müşteri Bazlı Teslimat" values={data.customerSummary.map((item) => [item.customer.name, `${item.deliveryCount} teslimat · ${item.totalQuantity.toLocaleString('tr-TR')} adet`])} />{data.items.length ? <><DeliveryRows data={data} /><Pagination page={page} data={data.pagination} onPage={onPage} /></> : <ReportEmpty title="Teslimat bulunamadı" icon={Truck} />}</div>; }
function DeliveryRows({ data }: { data: DeliveryReportData }) { return <section className="overflow-hidden rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)]"><div className="hidden lg:block"><table className="w-full"><thead><tr className="border-b border-[var(--zeva-border)] text-left text-xs text-[var(--zeva-text-muted)]"><th className="px-4 py-3">Tarih</th><th>Müşteri</th><th>İş Emri</th><th>Paket</th><th>Adet</th><th>Teslim Alan</th><th className="px-4">Durum</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id} className="border-b border-[var(--zeva-border)] last:border-0"><td className="px-4 py-3">{date(item.deliveredAt)}</td><td className="font-medium text-white">{item.customer.name}</td><td>{item.workOrderCount}</td><td>{item.packageCount}</td><td>{item.totalQuantity.toLocaleString('tr-TR')}</td><td>{item.receiverName ?? '—'}</td><td className="px-4"><Status cancelled={Boolean(item.cancelledAt)} /></td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 lg:hidden">{data.items.map((item) => <article key={item.id} className="rounded-lg border border-[var(--zeva-border)] bg-[#111512] p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-white">{item.customer.name}</h3><p className="mt-1 text-xs text-[var(--zeva-text-muted)]">{date(item.deliveredAt)} · {item.receiverName ?? 'Teslim alan belirtilmedi'}</p></div><Status cancelled={Boolean(item.cancelledAt)} /></div><p className="mt-3 text-sm">{item.workOrderCount} iş emri · {item.packageCount} paket · {item.totalQuantity.toLocaleString('tr-TR')} adet</p></article>)}</div></section>; }
function FinanceView({ query }: { query: ReturnType<typeof useFinanceReport> }) { if (query.isPending) return <Loading label="Finans raporu yükleniyor" />; if (query.isError || !query.data) return <ReportError title="Finans raporu yüklenemedi" />; const data = query.data; return <div className="space-y-4"><section><h2 className="mb-3 text-sm font-semibold text-white">Seçilen Dönem</h2><SummaryGrid values={[['İş Tutarı', formatMoney(data.period.workOrderTotal)], ['Tahsilat', formatMoney(data.period.paymentsTotal)], ['Borç Düzeltmesi', formatMoney(data.period.debitAdjustments)], ['Alacak / İndirim', formatMoney(data.period.creditAdjustments)]]} /></section><section><div className="mb-3"><h2 className="text-sm font-semibold text-white">Güncel Cari Durum</h2><p className="mt-1 text-xs text-[var(--zeva-text-muted)]">Bu değerler dönemden bağımsız bugünkü açık hesapları gösterir.</p></div><SummaryGrid values={[['Toplam Alacak', formatMoney(data.current.totalReceivable)], ['Müşteri Alacağı / Avans', formatMoney(data.current.totalCustomerCredit)]]} /></section></div>; }
function CustomersView({ query, page, onPage }: { query: ReturnType<typeof useCustomerReport>; page: number; onPage: (value: number) => void }) { const data = query.data; if (query.isPending) return <Loading label="Müşteri raporu yükleniyor" />; if (query.isError || !data) return <ReportError title="Müşteri raporu yüklenemedi" />; return data.items.length ? <div className="space-y-4"><CustomerRows data={data} /><Pagination page={page} data={data.pagination} onPage={onPage} /></div> : <ReportEmpty title="Müşteri bulunamadı" icon={UsersRound} />; }
function CustomerRows({ data }: { data: CustomerReportData }) { return <section className="overflow-hidden rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)]"><div className="hidden xl:block"><table className="w-full"><thead><tr className="border-b border-[var(--zeva-border)] text-left text-xs text-[var(--zeva-text-muted)]"><th className="px-4 py-3">Müşteri</th><th>İş Emri</th><th>Adet</th><th>İş Tutarı</th><th>Tahsilat</th><th>Cari Bakiye</th><th>Son İş</th><th className="px-4">Son Ödeme</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.customer.id} className="border-b border-[var(--zeva-border)] last:border-0"><td className="px-4 py-3 font-medium text-white">{item.customer.name}</td><td>{item.workOrderCount}</td><td>{item.totalQuantity.toLocaleString('tr-TR')}</td><td>{formatMoney(item.workOrderTotal)}</td><td>{formatMoney(item.paymentsTotal)}</td><td className="font-semibold">{formatBalance(item.balance)}</td><td>{date(item.lastWorkOrderAt)}</td><td className="px-4">{date(item.lastPaymentAt)}</td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 xl:hidden">{data.items.map((item) => <article key={item.customer.id} className="rounded-lg border border-[var(--zeva-border)] bg-[#111512] p-4"><h3 className="font-semibold text-white">{item.customer.name}</h3><p className="mt-1 text-sm font-semibold text-[var(--zeva-accent-strong)]">{formatBalance(item.balance)}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-[var(--zeva-text-muted)]">İş emri / adet</dt><dd className="mt-1">{item.workOrderCount} / {item.totalQuantity.toLocaleString('tr-TR')}</dd></div><div><dt className="text-[var(--zeva-text-muted)]">İş tutarı</dt><dd className="mt-1">{formatMoney(item.workOrderTotal)}</dd></div><div><dt className="text-[var(--zeva-text-muted)]">Tahsilat</dt><dd className="mt-1">{formatMoney(item.paymentsTotal)}</dd></div><div><dt className="text-[var(--zeva-text-muted)]">Son iş</dt><dd className="mt-1">{date(item.lastWorkOrderAt)}</dd></div></dl></article>)}</div></section>; }
function SummaryGrid({ values }: { values: Array<[string, string | number]> }) { return <section className="grid grid-cols-2 gap-2 lg:grid-cols-4">{values.map(([label, value]) => <article key={label} className="rounded-xl border border-[var(--zeva-border)] bg-[#111512] p-4"><p className="text-lg font-semibold text-white">{value}</p><p className="mt-1 text-xs text-[var(--zeva-text-muted)]">{label}</p></article>)}</section>; }
function Breakdown({ title, values }: { title: string; values: Array<[string, string | number]> }) { return <section className="rounded-xl border border-[var(--zeva-border)] bg-[var(--zeva-surface)] p-4"><h2 className="text-sm font-semibold text-white">{title}</h2>{values.length ? <dl className="mt-3 space-y-2">{values.map(([label, value]) => <div key={label} className="flex items-center justify-between gap-3 text-xs"><dt className="truncate text-[var(--zeva-text-muted)]">{label}</dt><dd className="shrink-0 font-semibold text-white">{value}</dd></div>)}</dl> : <p className="mt-3 text-xs text-[var(--zeva-text-muted)]">Kayıt bulunmuyor.</p>}</section>; }
function Pagination({ page, data, onPage }: { page: number; data: { totalPages: number }; onPage: (value: number) => void }) { const last = Math.max(1, data.totalPages); return <div className="flex items-center justify-between"><span className="text-xs text-[var(--zeva-text-muted)]">Sayfa {page} / {last}</span><div className="flex gap-2"><button aria-label="Önceki sayfa" disabled={page <= 1} onClick={() => onPage(page - 1)} className="grid size-10 place-items-center rounded-lg border border-[var(--zeva-border-strong)] disabled:opacity-35"><ChevronLeft className="size-4" /></button><button aria-label="Sonraki sayfa" disabled={page >= last} onClick={() => onPage(page + 1)} className="grid size-10 place-items-center rounded-lg border border-[var(--zeva-border-strong)] disabled:opacity-35"><ChevronRight className="size-4" /></button></div></div>; }
function Status({ cancelled }: { cancelled: boolean }) { return <span className={`rounded-full px-2 py-1 text-xs ${cancelled ? 'bg-[#342020] text-[#e7a3a3]' : 'bg-[#203326] text-[#a8d2b2]'}`}>{cancelled ? 'İptal Edildi' : 'Tamamlandı'}</span>; }
function Loading({ label }: { label: string }) { return <div aria-label={label} className="space-y-3"><Skeleton className="h-24" /><Skeleton className="h-72" /></div>; }
function ReportError({ title }: { title: string }) { return <EmptyState title={title} description="Veriler alınamadı. Lütfen tekrar deneyin." icon={RefreshCw} />; }
function ReportEmpty({ title, icon }: { title: string; icon: LucideIcon }) { return <EmptyState title={title} description="Seçilen dönem ve filtrelerle eşleşen kayıt bulunamadı." icon={icon} />; }
